[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "shanghai"

# Gas settings
gas_limit = 30_000_000
gas_price = 1_000_000_000  # 1 gwei

# Test settings
verbosity = 2
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15 }

# Formatter settings
line_length = 100
tab_width = 4
bracket_spacing = true

# RPC endpoints
[rpc_endpoints]
somnia = "${SOMNIA_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# Etherscan API keys for verification
[etherscan]
somnia = { key = "${SOMNIA_API_KEY}", url = "https://explorer.somnia.network/api" }

# Gas reports
gas_reports = ["Shootout"]

# Coverage settings
[profile.coverage]
verbosity = 2

# CI profile for faster testing
[profile.ci]
fuzz = { runs = 100 }
invariant = { runs = 32, depth = 10 }

# Local development profile
[profile.local]
verbosity = 3
gas_reports = ["*"]